services:
    wrytes-app:
        image: node:22-alpine
        working_dir: /app
        volumes:
            - .:/app
        command: sh -c "yarn install && yarn build && yarn start"
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
            - NEXT_PUBLIC_INDEXER_URL=${NEXT_PUBLIC_INDEXER_URL}
            - NEXT_PUBLIC_DERIBIT_AGENT_URL=${NEXT_PUBLIC_DERIBIT_AGENT_URL}
            - NEXT_PUBLIC_REOWN_PROJECT_ID=${NEXT_PUBLIC_REOWN_PROJECT_ID}
            - NEXT_PUBLIC_RPC_URL=${NEXT_PUBLIC_RPC_URL}
        restart: unless-stopped
